services:
  simpson-dl:
    build: .
    container_name: simpson_dl_container
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    restart: unless-stopped
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser --NotebookApp.token=''